# --- !Ups
CREATE TABLE "USERS" (
    "ID" SERIAL PRIMARY KEY, 
    "NAME" VARCHAR(255) NOT NULL
);

CREATE TABLE "ROTAS" (
    "NAME" VARCHAR(255) PRIMARY KEY, 
    "DESCRIPTION" VARCHAR(255), 
    "ASSIGNED_USER_ID" INT,
    FOREIGN KEY ("ASSIGNED_USER_ID") REFERENCES "USERS"("ID") ON DELETE SET NULL
);

CREATE TABLE "ROTA_USERS" (
    "ROTA_NAME" VARCHAR(255) NOT NULL,
    "USER_ID" INT NOT NULL,
    FOREIGN KEY ("ROTA_NAME") REFERENCES "ROTAS"("NAME") ON DELETE CASCADE, 
    FOREIGN KEY ("USER_ID") REFERENCES "USERS"("ID") ON DELETE CASCADE
);

# --- !Downs
DROP TABLE "ROTA_USERS";
DROP TABLE "USERS";
DROP TABLE "ROTAS" CASCADE;
