name: CI

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Digital Ocean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and test
        shell: bash
        working-directory: ./api
        run: sbt -v test

      - name: Build and tag Docker image
        shell: bash
        working-directory: ./api
        run: |
          sbt -v docker:publishLocal
          docker tag rota:latest registry.digitalocean.com/russellyeo/rota:latest

      - name: Deploy to Digital Ocean
        shell: bash
        working-directory: ./api
        run: |
          doctl registry login registry.digitalocean.com/russellyeo --expiry-seconds 100
          docker push registry.digitalocean.com/russellyeo/rota
