name: Deploy to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:  
  deploy:
    name: Deploy application to Fly.io
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: deploy-group
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_CONFIG_FILE: fly.production.toml
    steps:      
      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly
        run: flyctl deploy --remote-only --config $FLY_CONFIG_FILE